template_path: airflow-base.yaml
parameters:
  ServiceCatalogVersion: "3.9.1"
  EnvironmentName: "test"
  AirflowVersion: 2.2.2
  BucketNameSuffix: "code "
  DagS3Path: "care-and-services/engdataing-mwaa-dag/empty_folder"
  EnvironmentClass: "mw1.large"
  RequirementsS3Key: "care-and-services/engdataing-mwaa-dag/requirements.txt"
  MaxWorkers: "16"
  WeeklyMaintenanceWindowStart: "MON:00:00"
  CustomIAMRoleNameSuffix: airflow-execution-role
  PortfolioId: {{ var.PortfolioId }}
  CustomAirflowConfigurationsJSON: |
    {
      "webserver.default_ui_timezone": "America/Phoenix",
      "core.default_timezone":"America/Phoenix",
      "core.load_examples": "False",
      "core.enable_xcom_pickling": "True",
      "core.dag_file_processor_timeout":"100",
      "core.dagbag_import_timeout":"90",
      "smtp.smtp_host": "relay-app.secureserver.net",
      "smtp.smtp_mail_from": "no-reply-mwaa@godaddy.com",
      "smtp.smtp_port": "25",
      "smtp.smtp_ssl": "False",
      "smtp.smtp_starttls": "True"
    }
  TagsJSON: |
    {
      "Name": "driAirflow",
      "dataPipeline": "common",
      "organization": "DRI",
      "teamName": "dridata",
      "onCallGroup": "dri_data",
      "teamSlackChannel": "dridata-pipelines",
      "Demo": false
    }
  LoggingConfigurationsJSON: |
    {
       "DagProcessingLogs":{
          "Enabled": true,
          "LogLevel":"ERROR"
       },
       "SchedulerLogs":{
          "Enabled": true,
          "LogLevel":"INFO"
       },
       "TaskLogs":{
          "Enabled": true,
          "LogLevel":"INFO"
       },
       "WebserverLogs":{
          "Enabled": true,
          "LogLevel":"ERROR"
       },
       "WorkerLogs":{
          "Enabled": true,
          "LogLevel":"WARNING"
       }
    }
dependencies:
  - iam/mwaa-custom-role.yaml
